[package]
name = "actuire"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
rand = "0.8.5"
ratatui = "0.26.1"
structopt = "0.3.26"
typed-builder = "0.18.1"
